In [10]:
import pandas as pd
import numpy as np

In [11]:
# The average number of unsolved cubes in multi-BLD attempts (non DNF attempts)
results_path = 'WCA_export_Results.tsv'
results_df = pd.read_table(results_path)[['personId', 'eventId', 'value1', 'value2', 'value3']]
results_df.head()

     personId eventId  value1  value2  value3
0  2007AMAN01     333    1968    2203    2138
1  2004ROUA01     333    2222    2153    1731
2  2005SIMO01     333    3430    2581    2540
3  2007MALL01     333    2715    2452    2868
4  2007DESM01     333    2921    3184    2891

In [12]:
mbld_results = results_df[results_df['eventId'] == '333mbf'][['personId', 'value1', 'value2', 'value3']]

In [13]:
mbld_results['combined'] = mbld_results[['value1', 'value2', 'value3']].values.tolist()

In [14]:
mbld_results = mbld_results[['personId', 'combined']]

In [15]:
mbld_results = mbld_results.groupby('personId').agg(sum)

In [16]:
def calc_average_unsolved(x):
    def map_helper(result):
        return int(str(result)[-2:])
    valid_results = list(filter(lambda val: val > 0, x['combined'][0]))
    num_unsolved_list = list(map(map_helper, valid_results))
    return np.mean(num_unsolved_list)

num_unsolved_series = mbld_results.groupby('personId').apply(calc_average_unsolved)
mbld_results['mystery'] = num_unsolved_series
final_df = mbld_results[['mystery']]

/Users/riley/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/riley/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [17]:
final_df = final_df.reset_index().sort_values(by='mystery', ascending=False)
persons_path = "WCA_export_Persons.tsv"
persons_df = pd.read_table(persons_path)
final_df = final_df.merge(persons_df, how='left', left_on='personId', right_on='id')[['name', 'personId', 'mystery']]

In [18]:
final_df

                                           name    personId   mystery
0               Jefferson Andres Durango Argaez  2014ARGA02  8.400000
1                               Mark Boyanowski  2014BOYA01  8.015625
2                                William Wright  2015WRIG07  8.000000
3                                 Adrian Dębski  2017DEBS01  7.888889
4                            Yucheng Chen (陈裕铖)  2015CHEN49  7.632653
5                                    Tom Nelson  2013NELS01  7.588235
6                             Grigorii Alekseev  2015ALEK01  7.538462
7                                Graham Siggins  2016SIGG01  7.448276
8                                Aidan Proietto  2016PROI01  7.166667
9                              Kamil Przybylski  2016PRZY01  7.142857
10                            Aron Puddy-Mathew  2010PUDD01  7.000000
11                                 Tommy Cherry  2015CHER07  7.000000
12                             Qifan Wang (王启帆)  2017WANQ06  7.000000
13                       Sebastián Yuste Lucero  2017LUCE03  7.000000
14                              Zeshaan Khokhar  2015KHOK02  6.833333
15                                   Ben Bergen  2015BERG10  6.000000
16                                 Ramses Amaya  2014AMAY01  6.000000
17                                Pavel Jelínek  2014JELI01  6.000000
18                                Sydney Weaver  2013WEAV01  6.000000
19                                Shivam Bansal  2011BANS02  5.741935
20                                 Xin Shi (石欣)  2010SHIX01  5.687500
21                                  Zach Wilbur  2017WILB02  5.500000
22                Fernando Israel Zúñiga Macedo  2014MACE02  5.350000
23                                Kevin Montano  2011MONT02  5.250000
24                           Tomas Kristiansson  2007KRIS01  5.208333
25                            Wenxuan Yue (岳文轩)  2015YUEW01  5.125000
26                               Kamil Michalak  2016MICH01  5.111111
27                               Bin Huang (黄斌)  2011HUAN10  5.000000
28                                  Arrik Leman  2012LEMA02  5.000000
29                            Junwei Zhao (赵俊威)  2013ZHAO17  5.000000
...                                         ...         ...       ...
3123                                Niclas Mach  2018MACH13       NaN
3124                     Ethan Cai Money (钱蔡依神)  2018MONE02       NaN
3125                              Gladys Naylor  2018NAYL01       NaN
3126                               Wajdi Omrani  2018OMRA01       NaN
3127          Abylai Orazalin (Абылай Оразалин)  2018ORAZ01       NaN
3128     Nikita Ovsyannikov (Никита Овсянников)  2018OVSY01       NaN
3129           Platon Pechenev (Платон Печенев)  2018PECH01       NaN
3130                             Lewis Polansky  2018POLA01       NaN
3131                         Sebastian Pretzsch  2018PRET02       NaN
3132  Oleksandr Pryimakov (Олександр Приймаков)  2018PRYI01       NaN
3133                         Michael Ben Raziel  2018RAZI01       NaN
3134                         Corne van Rensburg  2018RENS01       NaN
3135     Danila Rogozhnikov (Данила Рогожников)  2018ROGO03       NaN
3136             Antonio Isaías Martínez Santos  2018SANT64       NaN
3137                                  Sora Sato  2018SATO01       NaN
3138                               Valerio Sepe  2018SEPE01       NaN
3139                        Zhenyang Shao (邵振洋)  2018SHAO02       NaN
3140                             Navanya Sharma  2018SHAR14       NaN
3141                           Roman V. Simkins  2018SIMK01       NaN
3142                                 John Smith  2018SMIT13       NaN
3143                             Łukasz Stępień  2018STEP04       NaN
3144                            Davron Takhirov  2018TAKH01       NaN
3145                           Yuxin Tang (唐宇鑫)  2018TANG03       NaN
3146                            Eric Waldbillig  2018WALD03       NaN
3147                               Roger Wanamo  2018WANA01       NaN
3148                          Kaijin Wang (王凯津)  2018WANK05       NaN
3149                               Joshua Wyatt  2018WYAT01       NaN
3150                               Lim Chun Yik  2018YIKL01       NaN
3151                             Ichwanto Yusro  2018YUSR02       NaN
3152                         Shukun Zhang (张树坤)  2018ZHAN34       NaN

[3153 rows x 3 columns]